### ISSUE TITLE
Use By Student

### ISSUE THREAD

**Issue by polymo1** [aydenp/PowerSchool-API#20]
Hello,

Am I correct in understanding that PowerSchool only provides API access to school staff?

I am interested in using the API to create a better frontend for personal use, and (in my opinion) the Student grade UI is ugly.

I am asking here, because if I would use the API, this is the project I would use, and I figure you would have an idea.

**Comment by aydenp** [comment]
I was using this library to build a site to retrieve my data as a student, so it should work!

**Comment by polymo1** [comment]
Thank you!
