### ISSUE TITLE
Add missing data

### ISSUE THREAD

**Issue by aydenp** [aydenp/PowerSchool-API#3]
- [x] Assignments
- [x] Assignment Categories
- [x] Attendance
- [x] Final grades

---

Thanks @reteps

**Comment by reteps** [comment]
you can use mine i dont really care. Can I email or discord them to you?

**Comment by aydenp** [comment]
Email's fine: github-a1@aydenp.website

**Comment by aydenp** [comment]
These are all now present in v1.1.0!

**Comment by reteps** [comment]
Awesome thanks! I’ll mirror the layout of the code similarly, except setup will be in 2 parts, “createClient” and “getStudent”

**Comment by reteps** [comment]
Do you want me to document or can you do that?
