### ISSUE TITLE
Use with React Native

### ISSUE THREAD

**Issue by Damako4** [aydenp/PowerSchool-API#7]
When I try using this API with React Native, the console logs the error that 
`Cannot read property 'split' of undefined`
The url for my code is here: https://snack.expo.io/@damako/powerschool

I used: `import _ from 'powerschool-api'` but an error shows

**Comment by Kgwenzi** [comment]
Hello

Currently its running with no errors. What is the expected behaviour because I  currently have a white screen with the output

> 
Teacher Name: BetancourtB

**Comment by aydenp** [comment]
Hey, I'm not too familiar with React Native but this should work with it. As @Kgwenzi says, I think this might be related to something else as your demo URL works. Please re-open if you still have the error!
